apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zot-registry
# zot-registry-config secret is not in Git; create it manually (see docs/zot-registry.md).
resources:
  - zot-registry-certificate.yaml
  - zot-registry-ingressroute.yaml
