apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zot-registry-tls
  namespace: zot-registry
spec:
  secretName: zot-registry-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - registry.tukangketik.net
